spring.application.name=foreign-relation

# JDBC URL k?t n?i ??n PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auctions
spring.datasource.username=postgres
spring.datasource.password=chienxom

# Lo?i driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialect phù h?p v?i PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate t? t?o / c?p nh?t b?ng (có th? ?? none n?u dùng flyway/liquibase)
spring.jpa.hibernate.ddl-auto=update

# Ghi log câu SQL (nên t?t ? production)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
